/**
 * Calendar — tender preparation events.
 *
 * Refs: brief §5 "Calendar", INT-A3
 * Parent routes (read from source at `8ff2e4c2`):
 *   GET /api/v1/tools/preparation-planner/events     -> {events[], authenticated?}
 *   GET /api/v1/tools/preparation-planner/suggested
 *
 * **This route returns 200 with `{events: [], authenticated: false}` when
 * there is no session** — it does not 401. That is the same trap as
 * `/api/auth/me` (audit gap A-4), and it matters here because an empty array
 * with a falsy flag is indistinguishable from "you have no events" unless the
 * flag is read. Rendering "nothing scheduled" at a signed-out user would hide
 * the real problem, so `authenticated: false` is surfaced as an unauthorized
 * error and handled like any other session loss.
 *
 * `isAutoGenerated` is kept and shown: brief §4.2 requires derived
 * information to declare its provenance, and an event the platform inferred
 * from a closing date is not the same as one the user entered.
 */

import { z } from "zod";
import { ApiError } from "../errors";
import { AuthenticatedEndpoint } from "./base";

const plannerEventSchema = z.object({
  id: z.string(),
  title: z.string(),
  description: z.string().nullable(),
  eventDate: z.string(),
  eventType: z.string(),
  isCompleted: z.boolean(),
  /** Minutes/hours before the event at which the parent notifies. */
  notifyBefore: z.number().optional(),
  /** Provenance: derived by the platform rather than entered (brief §4.2). */
  isAutoGenerated: z.boolean().optional(),
  source: z.string().nullable().optional(),
  tenderId: z.string().nullable().optional(),
});

export type PlannerEvent = z.infer<typeof plannerEventSchema>;

const eventsSchema = z.object({
  events: z.array(plannerEventSchema),
  /** Present and false when the caller has no session. */
  authenticated: z.boolean().optional(),
});

export class PlannerEndpoint extends AuthenticatedEndpoint {
  /**
   * @param tenderId Restricts to one tender's schedule when supplied.
   */
  async listEvents(
    tenderId?: string,
    signal?: AbortSignal,
  ): Promise<PlannerEvent[]> {
    const body = await this.transport.request({
      method: "GET",
      path: "/api/v1/tools/preparation-planner/events",
      query: { tenderId: tenderId || undefined },
      schema: eventsSchema,
      headers: await this.authHeaders(),
      signal,
    });

    // A 200 that says "not authenticated" is a session problem wearing a
    // success status. Reported as such so the shell drops to signed-out
    // rather than showing an empty calendar.
    if (body.authenticated === false) {
      throw new ApiError({
        kind: "unauthorized",
        message: "Not authenticated",
        status: 200,
      });
    }

    return body.events;
  }

  /** Events the platform proposes but the user has not accepted. */
  async listSuggested(signal?: AbortSignal): Promise<PlannerEvent[]> {
    const body = await this.transport.request({
      method: "GET",
      path: "/api/v1/tools/preparation-planner/suggested",
      schema: z.union([
        eventsSchema,
        z.object({ suggested: z.array(plannerEventSchema) }),
        z.array(plannerEventSchema),
      ]),
      headers: await this.authHeaders(),
      signal,
    });

    if (Array.isArray(body)) return body;
    if ("suggested" in body) return body.suggested;
    if (body.authenticated === false) {
      throw new ApiError({
        kind: "unauthorized",
        message: "Not authenticated",
        status: 200,
      });
    }
    return body.events;
  }
}

/** `SITE_VISIT` -> `Site visit`. */
export function describeEventType(eventType: string): string {
  const words = eventType.replace(/_/g, " ").toLowerCase().trim();
  if (!words) return "Event";
  return words.charAt(0).toUpperCase() + words.slice(1);
}

/**
 * Groups events into calendar buckets relative to `now`.
 *
 * Overdue is separated from upcoming rather than sorted in with it: an
 * incomplete event whose date has passed is a problem, not a past entry, and
 * burying it below today's items is how deadlines get missed.
 */
export function groupEvents(
  events: PlannerEvent[],
  now: Date = new Date(),
): {
  overdue: PlannerEvent[];
  today: PlannerEvent[];
  upcoming: PlannerEvent[];
  completed: PlannerEvent[];
} {
  const overdue: PlannerEvent[] = [];
  const today: PlannerEvent[] = [];
  const upcoming: PlannerEvent[] = [];
  const completed: PlannerEvent[] = [];

  const startOfToday = new Date(now);
  startOfToday.setHours(0, 0, 0, 0);
  const startOfTomorrow = new Date(startOfToday);
  startOfTomorrow.setDate(startOfTomorrow.getDate() + 1);

  for (const event of events) {
    if (event.isCompleted) {
      completed.push(event);
      continue;
    }
    const when = new Date(event.eventDate);
    if (Number.isNaN(when.getTime())) {
      // An unusable date must not silently vanish; treat it as upcoming so
      // the user still sees the event exists.
      upcoming.push(event);
      continue;
    }
    if (when < startOfToday) overdue.push(event);
    else if (when < startOfTomorrow) today.push(event);
    else upcoming.push(event);
  }

  const byDate = (a: PlannerEvent, b: PlannerEvent) =>
    new Date(a.eventDate).getTime() - new Date(b.eventDate).getTime();

  return {
    overdue: overdue.sort(byDate),
    today: today.sort(byDate),
    upcoming: upcoming.sort(byDate),
    completed: completed.sort(byDate),
  };
}
