import { AsyncSection, Panel } from "../../components/common/AsyncSection";
import { useAsync } from "../../hooks/use-async";
import {
  describeEventType,
  groupEvents,
  type PlannerEndpoint,
  type PlannerEvent,
} from "../../services/api/endpoints/planner";
import { formatEventDate } from "./event-format";

export interface CalendarProps {
  endpoint: PlannerEndpoint;
}

/**
 * Calendar (brief §5) — tender preparation events.
 *
 * **Overdue is a separate group, above everything else.** An incomplete event
 * whose date has passed is a problem, not history, and sorting it in
 * chronologically buries it below today's items — which is how site visits and
 * clarification deadlines get missed.
 *
 * Auto-generated events are labelled as such (brief §4.2, provenance): an
 * event the platform inferred from a closing date is not the same as one a
 * person entered, and the user should know which they are looking at.
 */
export function Calendar({ endpoint }: CalendarProps) {
  const state = useAsync(
    (signal) => endpoint.listEvents(undefined, signal),
    [endpoint],
  );

  return (
    <section aria-labelledby="calendar-heading" className="max-w-3xl">
      <h1
        id="calendar-heading"
        className="text-xl font-semibold text-foreground"
      >
        Calendar
      </h1>
      <p className="mt-2 text-sm text-muted-foreground">
        Site visits, clarification deadlines and submission dates.
      </p>

      <div className="mt-6">
        <AsyncSection
          state={state}
          subject="your calendar"
          onRetry={state.reload}
          empty={
            <p className="text-sm text-muted-foreground">
              Nothing is scheduled. Preparation events appear here once you
              start an application.
            </p>
          }
        >
          {(events) => {
            const groups = groupEvents(events);
            return (
              <div className="flex flex-col gap-4">
                {groups.overdue.length > 0 && (
                  <Panel title={`Overdue (${groups.overdue.length})`}>
                    <EventList events={groups.overdue} overdue />
                  </Panel>
                )}
                {groups.today.length > 0 && (
                  <Panel title="Today">
                    <EventList events={groups.today} />
                  </Panel>
                )}
                {groups.upcoming.length > 0 && (
                  <Panel title="Upcoming">
                    <EventList events={groups.upcoming} />
                  </Panel>
                )}
                {groups.completed.length > 0 && (
                  <Panel title={`Completed (${groups.completed.length})`}>
                    <EventList events={groups.completed} />
                  </Panel>
                )}
              </div>
            );
          }}
        </AsyncSection>
      </div>
    </section>
  );
}

function EventList({
  events,
  overdue = false,
}: {
  events: PlannerEvent[];
  overdue?: boolean;
}) {
  return (
    <ul className="flex flex-col gap-2">
      {events.map((event) => (
        <li key={event.id} className="flex items-start justify-between gap-4">
          <div className="min-w-0">
            <p className="text-sm text-card-foreground">
              {event.title}
              {event.isAutoGenerated && (
                // Provenance (brief §4.2): the platform inferred this event.
                <span className="ml-2 text-xs font-normal text-muted-foreground">
                  added automatically
                </span>
              )}
            </p>
            <p className="text-sm text-muted-foreground">
              {describeEventType(event.eventType)}
              {event.description ? ` · ${event.description}` : ""}
            </p>
          </div>
          <span
            className={
              overdue
                ? "shrink-0 text-sm font-medium text-destructive"
                : "shrink-0 text-sm text-muted-foreground"
            }
          >
            {formatEventDate(event.eventDate)}
          </span>
        </li>
      ))}
    </ul>
  );
}
